### ISSUE TITLE
NanoMod after NanoPreprocessSimple

### ISSUE THREAD

**Issue by yasukoh** [biocorecrg/master_of_pores#70]
Hi,

Sorry to bother you again.  I would like to do NanoMod module after NanoPreprocessSimple, but no files in alignment folder of output folder and more importantly, no demultiplexed fast5 files. With that I don't think I can do NanoMod module.. 
I missed to do something? or could you give me any suggestions what I should do?

thank you so much.

yh

**Comment by lucacozzuto** [comment]
Hi, NanoMod runs after nanopreprocess. If you want to use nanopreprocess simple you have to recreate the same folder structure produced by nanopreprocess. There is a script called reorganize.sh within nanopreprocess/bin for demultiplexed runs. PS: you should have alignments after nanopreprocess simple or did you inactivate that step?

**Comment by yasukoh** [comment]
Hi, of course I didn't inactivate the alignment step. There is cram files folder and .cram and .crai files are in, but no files in alignment folder. Are those supposed to clean up after converted to cram files? 

for reorganize.sh, again maybe very basic question, but could you tell me how I should run this? I cannot run as normal shell script I know. 
I appreciate your help.

yh

**Comment by lucacozzuto** [comment]
Hi, thanks it was a bug with copying the alignment in the folder. I fixed in https://github.com/biocorecrg/master_of_pores/commit/89fc6eaeab345651369020d2ecd37a22236277c2. So you can do a git pull and a nextflow -resume to copy the missing files.
Let me know.

**Comment by yasukoh** [comment]
Yes, now I can see .bam and .bai files in alignment folders. 
But I still cannot work reorganize.sh. I cannot run this script as a normal shell script and I got an error when trying to run with nextflow.
saying,
---
Script compilation error
- file : /master_of_pores-review/NanoPreprocessSimple/bin/reorganize.sh
- cause: expecting '(', found '[' @ line 3, column 4.
   if [ x"$1" == x ]; then
      ^

1 error
----
Could you give me any suggestions what I should do with?

Thank you so much for your help.

yh

**Comment by lucacozzuto** [comment]
Hi, the reorganize.sh actually works only for NanoPreprocess. 
This is because you need in principle demultiplexed fast5 and fastq to be sent to NanoMod process and they are generated only in NanoPreprocess module.
Sorry for the inconvenience.

**Comment by yasukoh** [comment]
Ouch, I had to do all over again..
OK. will do.
Thank you for your help.

yh
